"use client";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ArrowUpRight, ArrowDownRight, Gem, Activity, BarChart2, ArrowRight, Zap, TrendingUp } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { MOCK_SIGNALS } from "@/lib/mock";
import { MarketTicker } from "@/components/market-ticker";

export default function MarketPage() {
    const segments = ['All', 'Equity', 'Crypto', 'Commodity'];

    return (
        <div className="flex flex-col min-h-screen bg-background text-foreground selection:bg-primary/30 transition-colors duration-300">

            {/* <MarketTicker /> */}

            {/* Background Grid & Spotlights */}
            <div className="absolute inset-0 z-0 w-full h-full pointer-events-none">
                <div className="absolute inset-0 bg-[linear-gradient(to_right,hsl(var(--border))_1px,transparent_1px),linear-gradient(to_bottom,hsl(var(--border))_1px,transparent_1px)] bg-[size:24px_24px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] opacity-[0.2]"></div>
                <div className="absolute top-0 left-0 right-0 h-[500px] w-full bg-gradient-to-b from-primary/5 via-transparent to-transparent blur-3xl opacity-40"></div>
            </div>

            <div className="w-full max-w-7xl mx-auto mt-10 px-6 py-16 md:py-24 relative z-10">
                {/* Modern Hero Header */}
                <div className="flex flex-col md:flex-row justify-between items-end gap-8 mb-20">
                    <div className="space-y-6 max-w-3xl">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-semibold uppercase tracking-wider animate-in fade-in slide-in-from-bottom-4 duration-500">
                            <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span>
                            Live Intel Feed
                        </div>
                        <h1 className="text-5xl md:text-8xl font-heading font-bold tracking-tighter leading-[0.9] text-slate-900 dark:text-white">
                            Market <br />
                            <span className="text-transparent bg-clip-text bg-gradient-to-br from-primary via-primary/80 to-primary/50 filter drop-shadow-sm">Alpha</span>
                            <span className="text-primary">.</span>
                        </h1>
                        <p className="text-lg text-slate-600 dark:text-slate-400 max-w-xl leading-relaxed border-l-2 border-slate-200 dark:border-white/10 pl-6">
                            High-fidelity signals generated by our proprietary algorithms.
                            Track setups, analyze risk, and execute with precision.
                        </p>
                    </div>

                    <div className="hidden md:flex gap-8 p-6 rounded-2xl bg-card/40 backdrop-blur-xl border border-primary/20 shadow-2xl shadow-primary/5">
                        <div>
                            <div className="text-sm text-muted-foreground mb-1">Active Signals</div>
                            <div className="text-3xl font-mono font-bold text-foreground flex items-center gap-2">
                                12 <span className="text-sm text-green-600 dark:text-green-500 px-2 py-0.5 rounded-full bg-green-100 dark:bg-green-500/10">+4 today</span>
                            </div>
                        </div>
                        <div className="w-px h-12 bg-border/50"></div>
                        <div>
                            <div className="text-sm text-muted-foreground mb-1">Avg Accuracy</div>
                            <div className="text-3xl font-mono font-bold text-foreground">94.2%</div>
                        </div>
                    </div>
                </div>

                {/* Content Tabs */}
                <Tabs defaultValue="All" className="w-full space-y-10">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 border-b border-slate-200 dark:border-white/10 pb-6">
                        <TabsList className="bg-transparent p-0 h-auto gap-2 flex-wrap justify-start">
                            {segments.map(seg => (
                                <TabsTrigger
                                    key={seg}
                                    value={seg}
                                    className="px-5 py-2 rounded-full border border-slate-200 dark:border-white/5 bg-white dark:bg-white/5 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-white/10 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:font-bold data-[state=active]:border-primary transition-all duration-300 shadow-sm dark:shadow-none"
                                >
                                    {seg}
                                </TabsTrigger>
                            ))}
                        </TabsList>

                        <div className="flex items-center gap-2 text-sm text-slate-500 dark:text-slate-500">
                            <Clock className="w-4 h-4" />
                            <span>Last updated: <span className="text-slate-900 dark:text-white font-mono">Just now</span></span>
                        </div>
                    </div>

                    {segments.map(seg => (
                        <TabsContent key={seg} value={seg} className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 fill-mode-both">
                            <div className="grid gap-8 md:gap-10 sm:grid-cols-2 lg:grid-cols-3">
                                {MOCK_SIGNALS.filter(s => seg === 'All' || s.segment === seg).map((signal, i) => (
                                    <Card key={signal.id} className="relative overflow-hidden rounded-[2rem] bg-white dark:bg-zinc-900/50 border border-slate-100 dark:border-white/5 transition-all duration-500 group shadow-[0_8px_40px_-12px_rgba(0,0,0,0.1)] hover:shadow-[0_20px_60px_-12px_rgba(0,0,0,0.15)] dark:shadow-none hover:-translate-y-1">

                                        {/* Abstract Card BG */}
                                        <div className="absolute inset-0 bg-gradient-to-b from-slate-50/50 dark:from-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>

                                        <CardHeader className="p-6 pb-0 relative z-10 flex flex-row justify-between items-start space-y-0">
                                            <div>
                                                <Badge variant="secondary" className="mb-3 rounded-full bg-slate-100 dark:bg-white/10 text-slate-500 dark:text-slate-300 font-medium px-4 py-1.5 uppercase tracking-wider text-[11px] shadow-sm">
                                                    {signal.segment}
                                                </Badge>
                                                <CardTitle className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white group-hover:text-primary transition-colors">
                                                    {signal.symbol}
                                                </CardTitle>
                                                {signal.status === 'Open' && (
                                                    <div className="flex items-center gap-2 mt-2">
                                                        <span className="relative flex h-2.5 w-2.5">
                                                            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                                                            <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-green-500"></span>
                                                        </span>
                                                        <span className="text-xs font-medium text-green-500 uppercase tracking-wide">Live Signal</span>
                                                    </div>
                                                )}
                                            </div>

                                            <div className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-bold uppercase tracking-wider shadow-sm ${signal.type === 'BUY'
                                                ? 'bg-green-50 text-green-700 dark:bg-green-500/20 dark:text-green-400 border border-green-200 dark:border-green-500/20'
                                                : 'bg-red-50 text-red-700 dark:bg-red-500/20 dark:text-red-400 border border-red-200 dark:border-red-500/20'
                                                }`}>
                                                {signal.type === 'BUY' ? <ArrowUpRight className="w-3.5 h-3.5" /> : <ArrowDownRight className="w-3.5 h-3.5" />}
                                                {signal.type}
                                            </div>
                                        </CardHeader>

                                        <CardContent className="p-6 relative z-10">
                                            <div className="flex items-end justify-between mb-6 pb-6 border-b border-slate-100 dark:border-white/5 border-dashed">
                                                <div>
                                                    <div className="text-xs font-semibold text-slate-400 mb-1.5 uppercase tracking-wide">Entry Price</div>
                                                    <div className="text-4xl font-bold text-slate-900 dark:text-white tracking-tighter tabular-nums">
                                                        {signal.entry.toLocaleString()}
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="grid grid-cols-2 gap-3">
                                                <div className="p-3 rounded-xl bg-red-50/50 dark:bg-red-500/5 transition-colors">
                                                    <div className="text-[10px] font-bold text-red-600/70 dark:text-red-400/70 mb-1 flex items-center gap-1 uppercase tracking-widest">
                                                        <Activity className="w-3 h-3" /> Stop Loss
                                                    </div>
                                                    <div className="text-lg font-bold text-slate-900 dark:text-white tabular-nums">{signal.stopLoss.toLocaleString()}</div>
                                                </div>
                                                <div className="p-3 rounded-xl bg-green-50/50 dark:bg-green-500/5 transition-colors">
                                                    <div className="text-[10px] font-bold text-green-600/70 dark:text-green-400/70 mb-1 flex items-center gap-1 uppercase tracking-widest">
                                                        <TrendingUp className="w-3 h-3" /> Target
                                                    </div>
                                                    <div className="text-lg font-bold text-slate-900 dark:text-white tabular-nums">{signal.targets[0].toLocaleString()}</div>
                                                </div>
                                            </div>

                                            {/* PnL Tag if closed */}
                                            {signal.status !== 'Open' && signal.pnl !== 0 && (
                                                <div className="mt-4 flex justify-between items-center bg-slate-50 dark:bg-white/5 rounded-lg p-2.5 px-4">
                                                    <span className="text-xs font-medium text-slate-500 uppercase tracking-wide">Net Result</span>
                                                    <span className={`text-base font-bold ${signal.pnl > 0 ? 'text-green-600 dark:text-green-500' : 'text-red-600 dark:text-red-500'}`}>
                                                        {signal.pnl > 0 ? '+' : ''}{signal.pnl} pts
                                                    </span>
                                                </div>
                                            )}
                                        </CardContent>

                                        {/* Premium Overlay */}
                                        {/* Premium Overlay */}
                                        {!signal.isFree && (
                                            <div className="absolute inset-0 z-20 flex flex-col items-center justify-center bg-white/60 dark:bg-black/60 backdrop-blur-xl p-6 text-center transition-all duration-300">
                                                <div className="w-16 h-16 rounded-[1.5rem] bg-white dark:bg-zinc-900 shadow-[0_20px_50px_-12px_rgba(0,0,0,0.1)] ring-1 ring-slate-100 dark:ring-white/10 flex items-center justify-center mb-4 transform group-hover:scale-110 transition-transform duration-500">
                                                    <Gem className="w-7 h-7 text-primary drop-shadow-md" />
                                                </div>
                                                <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2">Premium Alpha</h3>
                                                <p className="text-sm text-slate-500 dark:text-slate-400 mb-6 max-w-[200px] leading-relaxed">
                                                    Institutional grade signals with higher win-rates.
                                                </p>
                                                <Link href="/plans" className="w-full max-w-[180px]">
                                                    <Button size="lg" className="w-full rounded-full bg-slate-900 dark:bg-white text-white dark:text-black font-bold h-11 text-sm shadow-xl shadow-slate-200/50 dark:shadow-none hover:scale-105 transition-transform">
                                                        Unlock Access <ArrowRight className="w-4 h-4 ml-2" />
                                                    </Button>
                                                </Link>
                                            </div>
                                        )}
                                    </Card>
                                ))}
                            </div>
                        </TabsContent>
                    ))}
                </Tabs>
            </div>
        </div>
    );
}

function Clock(props: any) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="12" cy="12" r="10" />
            <polyline points="12 6 12 12 16 14" />
        </svg>
    )
}
